### ISSUE TITLE
NSwagStudio - Requested value 'x-swagger-router-controller' was not found.

### ISSUE THREAD

**Issue by cjfphilip** [RSuter/NSwag#1048]
Hi there, I have yet to debug the code myself, but thought I just raise this as an issue which I'm not sure of a solution to yet.

I have a Swagger Document that starts like this:

    {
      "swagger": "2.0",
      "x-access": [
        "INTERNAL",
        "APP",
        "INTERNAL"
      ],
      "info": {
        "version": "1.0.1",
        "title": "***",
        "description": "***",
        "contact": {
          "name": "API-Team",
          "email": "API-Team@***.com"
        }
      },
      "basePath": "/v1/customer",
      "tags": [
        {
          "name": "***",
          "description": "***"
        }
      ],
      "schemes": [
        "https"
      ],
      "produces": [
        "application/json"
      ],
      "securityDefinitions": {
        "api_key": {
          "type": "apiKey",
          "name": "X-API-Key",
          "in": "header"
        },
        "oauth_application": {
          "type": "oauth2",
          "tokenUrl": "***",
          "flow": "application"
        },
        "oauth_password": {
          "type": "oauth2",
          "tokenUrl": "***",
          "flow": "password"
        }
      },
      "paths": {
        "/customers": {
          "x-swagger-router-controller": "customers",
          "get": {
          .................

...etc

When I try generate the c-sharp client I get this error:

    System.ArgumentException: Requested value 'x-swagger-router-controller' was not found.

    Runtime: Default
       at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
       at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
       at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
       at NSwag.SwaggerOperations.SwaggerOperationsJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
       at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at NSwag.SwaggerDocument.<FromJsonAsync>d__70.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.<RunAsync>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.<RunAsync>d__8.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NConsole.CommandLineProcessor.Process(String[] args, Object input)
       at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)

some of the swagger specs that I have that don't use x-swagger-router-controller are fine. I tried simply removing the x-swagger-router-controller but that simply raised another error, is there a work around for this? I don't actually understand the error.

Thanks
Charles

**Comment by RSuter** [comment]
NSwag tries to map all operations in a path object to a HTTP method and this fails. For now, you have to remove your custom `x-swagger-router-controller` properties...

**Comment by cjfphilip** [comment]
Thanks for your quick reply! I have removed them all, the next error I receive is that the requested value "x-a127-apply" was not found. I then removed this as well and it worked. So thanks so much for your help!

**Comment by RSuter** [comment]
Reopened: Should be fixed => Add extension properties to ExtensionData...
