### ISSUE TITLE
InvalidCastException while parsing Gitea-Swagger-document

### ISSUE THREAD

**Issue by Chri-s** [RSuter/NSwag#1171]
I'm trying to generate a C# client for the gitea API.

The line
`var document = await SwaggerDocument.FromUrlAsync(@"https://try.gitea.io/swagger.v1.json");`
throws this exception:

```
System.InvalidCastException: Unable to cast object of type 'NSwag.SwaggerResponse' to type 'NJsonSchema.JsonSchema4'.
   at NJsonSchema.References.JsonReferenceBase`1.NJsonSchema.References.IJsonReferenceBase.set_Reference(IJsonReference value)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.<VisitJsonReferenceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitPropertiesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Visitors.JsonReferenceVisitorBase.<VisitAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchemaReferenceUtilities.JsonReferenceUpdater.<VisitAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchemaReferenceUtilities.<UpdateSchemaReferencesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerDocument.<FromJsonAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerDocument.<FromUrlAsync>d__72.MoveNext()
```

I'm new to swagger, NSwag and gitea and have absolutely no idea what is wrong.
I shortened the document to a minimal version which only contains the /version path and it works.

**Comment by Chri-s** [comment]
I think i narrowed it down:
If a path has a response consisting only of an http status code and a reference, it works:
```
"responses": {
    "200": {
        "$ref": "#/responses/Hook"
    }
}
```

If the response has the $ref in a schema object, the exception is thrown:
```
"responses": {
    "204": {
        "description": "user is a public member",
        "schema": {
            "$ref": "#/responses/empty"
        }
    }
```

If I move the $ref one level up and leave the description, it works:
```
"responses": {
    "204": {
        "description": "user is a public member",
        "schema": {
            "$ref": "#/responses/empty"
        }
    }
```

I don't know if the swagger document is invalid or if this is a bug, but perhaps this info helps debugging.

**Comment by RSuter** [comment]
This is clearly a bug: It seems that "emtpy" is deserialized as schema and not as response...

**Comment by RSuter** [comment]
I think the problem is as follows: The reference resolver tries to replace the object with a ref with the actual object, this works for the first and last one because it has no other properties... However the behavior is different for broken $refs (the $ref keyword cannot be used with other properties): I think NJS/NSwag tries to assign the referenced response to the "schema" property which fails because it is a SwaggerResponse and not a JsonSchema4

**Comment by Chri-s** [comment]
Wow, thanks for the quick answer! 😃 👍

**Comment by RSuter** [comment]
The main problem is that the deserializer currently instantiated the objects of definitions, responses, etc eagerly - but it should deserialize it lazily at the time when the type is determined by a $ref - so that your scenario is supported. However this is essentially a rewrite of the whole $ref handling/resolution code... 

At the moment i’d recommend to write a small cmd app to transform the spec before feeding it into nswag..
