### ISSUE TITLE
WebAPI2Swagger - Newtonsoft binding error on Linux

### ISSUE THREAD

**Issue by CastSeven** [RSuter/NSwag#1177]
**NSwag Version**: 11.13.1
**Linux Distros Tested**: Debian 9, Centos 7

When attempting to use the WebAPI2Swagger module in NSwag on a Linux environment using .NET Core 2.0, an assembly binding error is received:
```
root@8b90afbcf53a:/source# dotnet ./NSwag/NetCore20/dotnet-nswag.dll run /variables:Configuration=Debug
NSwag command line tool for .NET Core NetCore20, toolchain v11.13.1.0 (NJsonSchema v9.10.19.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: source/NSwag/NetCore20

Executing file 'nswag.json'...
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe
6b2a6aeed'. The system cannot find the path specified.

File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GetControllerClasses(Assembly assembly) in C:\projects\nswag\src\NSwag.Swagger
Generation.WebApi\WebApiToSwaggerGenerator.cs:line 50
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.GetControllerNames(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSw
ag.Commands\Commands\SwaggerGeneration\WebApiToSwaggerCommand.cs:line 261
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.<RunIsolatedAsync>d__88.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Com
mands\SwaggerGeneration\WebApiToSwaggerCommand.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPath
s, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 59
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.<RunIsolatedAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase.<RunAsync>d__4.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwa
ggerOutputCommandBase.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__40.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentB
ase.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__4.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\
Document\ExecuteDocumentCommand.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Document\Exe
cuteDocumentCommand.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

For convenience, this can also be reproduced with a Docker container using microsoft/aspnetcore-build:2.0.0 as a base.

Note that this appears to occur whether or not the steps listed here for ASP.NET Core projects are taken:   https://github.com/RSuter/NSwag/wiki/Assembly-loading#net-core.  This particular issue seems more about the environment than the assembly being targeted.

**Comment by RSuter** [comment]
Did you check whether the missing library is in the output directory or in one of the referencePaths?

**Comment by RSuter** [comment]
v11.14.0: 

We improved the assembly loader (mainly for .NET Core) so that it runs in a more isolated space and the loaded DLLs should better match the requested versions. Please test this with your projects to ensure that we didnt introduce regressions. 

Important if you have DLL loading problems: 

- Check that the DLL in question is available in the output directory (where the selected assembly is located) or in ReferencePaths
- Check that you selected the correct runtime: Either in NSwagStudio UI, as /runtime parameter in the NPM CLI or execute the correct exe binary

For more information regarding assembly loading: https://github.com/RSuter/NSwag/wiki/Assembly-loading

Main commit: https://github.com/RSuter/NSwag/commit/04576e4d1b714ac5bd9b5df11d72469a23f7c0ff#diff-14dafe6661bab407ae5c0d7095ccd1f4

**Comment by CastSeven** [comment]
@RSuter - I just re-tested on v11.14 and now I'm getting a slightly different issue.  It seems it's trying to provide the correct path for assembly binding but appending the working folder twice:

```
root@789175dbd022:/source# dotnet NSwagTest/NetCore20/dotnet-nswag.dll run /variables:Configuration=Debug
NSwag command line tool for .NET Core NetCore20, toolchain v11.14.0.0 (NJsonSchema v9.10.24.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: source/NSwagTest/NetCore20

Executing file 'nswag.json'...
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe
6b2a6aeed'. The system cannot find the path specified.

File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.IO.DirectoryNotFoundException:
Could not find a part of the path '/source/source/NSwagTest/NetCore20'.
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget s
earchTarget, Func`3 translateResult)
   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Bo
olean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NSwag.AssemblyLoader.AssemblyLoader.TryLoadByVersion(List`1 allReferencePaths, String assemblyName, String assemblyVersion) in C:\proj
ects\nswag-25x6o\src\NSwag.AssemblyLoader\AssemblyLoader.cs:line 156
   at NSwag.AssemblyLoader.AssemblyLoader.<>c__DisplayClass6_0.<RegisterReferencePaths>b__1(AssemblyLoadContext context, AssemblyName args)
in C:\projects\nswag-25x6o\src\NSwag.AssemblyLoader\AssemblyLoader.cs:line 134
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssembly(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GetControllerClasses(Assembly assembly) in C:\projects\nswag-25x6o\src\NSwag.S
waggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 50
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.GetControllerNames(AssemblyLoader assemblyLoader) in C:\projects\nswag-25x6o\s
rc\NSwag.Commands\Commands\SwaggerGeneration\WebApiToSwaggerCommand.cs:line 261
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.<RunIsolatedAsync>d__88.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Comman
ds\Commands\SwaggerGeneration\WebApiToSwaggerCommand.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPath
s, String[] referencePaths) in C:\projects\nswag-25x6o\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 59
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.<RunIsolatedAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase.<RunAsync>d__4.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Commands\Commands\Isola
tedSwaggerOutputCommandBase.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__40.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Commands\NSwagDoc
umentBase.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__4.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Commands\NSwagDocument.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Commands\Com
mands\Document\ExecuteDocumentCommand.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext() in C:\projects\nswag-25x6o\src\NSwag.Commands\Commands\Docume
nt\ExecuteDocumentCommand.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag-25x6o\src\NSwag.Commands\NSwagCommandProcessor.cs:lin
e 54
```

**Comment by RSuter** [comment]
Please retest with v11.15

**Comment by CastSeven** [comment]
Just re-tested with v11.15.1, and it seems like I'm having essentially the same problem but with a different assembly (this time, one that's part of my application):

```
root@b8b80dbf8b71:/source# dotnet NSwagTest/NetCore20/dotnet-nswag.dll run /variables:Configuration=Debug
NSwag command line tool for .NET Core NetCore20, toolchain v11.15.1.0 (NJsonSchema v9.10.26.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: source/NSwagTest/NetCore20

Executing file 'nswag.json'...
System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e6
04'. The system cannot find the path specified.

File name: 'AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' ---> System.IO.DirectoryNotFoundException: Could n
ot find a part of the path '/source/source/NSwagTest/NetCore20'.
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget s
earchTarget, Func`3 translateResult)
   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Bo
olean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NSwag.AssemblyLoader.CustomAssemblyLoadContext.TryLoadByVersion(List`1 allReferencePaths, String assemblyName, String assemblyVersion)
 in C:\projects\nswag\src\NSwag.AssemblyLoader\CustomAssemblyLoadContext.cs:line 107
   at NSwag.AssemblyLoader.CustomAssemblyLoadContext.Load(AssemblyName args) in C:\projects\nswag\src\NSwag.AssemblyLoader\CustomAssemblyLoa
dContext.cs:line 49
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int3
2* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& n
amedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, Run
timeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<>c__DisplayClass14_0.<GetActionMethods>b__1(MethodInfo m) in C:\projects\nswa
g\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 244
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllerAsync>d__11.MoveNext() in C:\projects\nswag\src\NSwag.Sw
aggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllersAsync>d__9.MoveNext() in C:\projects\nswag\src\NSwag.Sw
aggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.SwaggerGeneration.WebApiToSwaggerCommand.<RunIsolatedAsync>d__88.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Com
mands\SwaggerGeneration\WebApiToSwaggerCommand.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPath
s, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedCommandBase`1.<RunIsolatedAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase.<RunAsync>d__4.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwa
ggerOutputCommandBase.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocumentBase.<GenerateSwaggerDocumentAsync>d__40.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentB
ase.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__4.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\
Document\ExecuteDocumentCommand.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Document\Exe
cuteDocumentCommand.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

**As before, the /source path is included twice.**

As a test, I tried going up to the root level and running from there instead, and this appears to work -- however, because of the way my containerized builds work I'm not sure I can use this as a true workaround:

```
root@b8b80dbf8b71:/source# cd ..
root@b8b80dbf8b71:/# dotnet /source/NSwagTest/NetCore20/dotnet-nswag.dll run source/nswag.json /variables:Configuration=Debug
NSwag command line tool for .NET Core NetCore20, toolchain v11.15.1.0 (NJsonSchema v9.10.26.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: source/NSwagTest/NetCore20

Executing file 'source/nswag.json'...
Done.

Duration: 00:00:01.7053179
```

**Comment by RSuter** [comment]
Ok now it seems that its just a path problem jnder linux and not an assembly loader problem...

**Comment by RSuter** [comment]
I suspect it's either 

https://github.com/RSuter/NSwag/blob/493a92e201ed8fb64d65901a8b92175a691c8970/src/NSwag.Commands/Commands/IsolatedCommandBase.cs#L71

or

https://github.com/RSuter/NSwag/blob/46f71b6c0004f6bcf3d67674bedd5f0fdb02f360/src/NSwag.AssemblyLoader/AssemblyLoader.cs#L84

what do you think?

**Comment by CastSeven** [comment]
I think I found the problem.  I wasn't able to directly debug due to a known issue in the VS docker support, but by adding some logging I noticed the following:
```
root@e5c6debead66:/source# dotnet NSwagTest/dotnet-nswag.dll run /variables:Configuration=Debug
NSwag command line tool for .NET Core NetCore20, toolchain v11.15.1.0 (NJsonSchema v9.10.26.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: source/NSwagTest

Executing file 'nswag.json'...
=============================
DEBUG - GetAllReferencePaths:
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0
=============================
=============================
DEBUG: RegisterReferencePaths
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/wwwroot
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/app
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/refs
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/wwwroot/css
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/unix
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-x64
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-arm
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-armel
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/osx
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-x64
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-arm64
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-x86
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-arm
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-arm/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-x86/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-arm64/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win-x64/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/osx/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-armel/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win/lib
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/win/lib/netstandard1.3
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-arm/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/linux-x64/native
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/unix/lib
/source/MyAspNetCoreApp/bin/Debug/netcoreapp2.0/publish/runtimes/unix/lib/netstandard1.3
source/NSwagTest
=============================
System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e6
04'. The system cannot find the path specified.
```

The last path in RegisterReferencePaths is missing a leading slash, which is due to the 2nd line you listed.  Correcting this appears to correct the issue and with my locally modified version using this change I was able to successfully generate on Linux!

Due to company policy, I cannot submit a PR at this time, but here's the changed line:
```csharp
allReferencePaths.Add(Path.GetDirectoryName(typeof(AssemblyLoader).GetTypeInfo().Assembly.CodeBase.Replace("file:///", "/"))); 
```

**Comment by RSuter** [comment]
Thank you for looking into this... I think your change would break Windows users. Is there a method to root this so that it works in any environment?

**Comment by CastSeven** [comment]
Ugh, yeah you're right, just tested it on windows.  I'll see what I can come up with.

**Comment by CastSeven** [comment]
Found a simpler fix, and this works on both Windows and Linux:

```
allReferencePaths.Add(Path.GetDirectoryName(typeof(AssemblyLoader).GetTypeInfo().Assembly.Location));
```

The Assembly.Location property returns a platform-valid path, which Path.GetDirectoryName handles correctly depending on the platform as well.  So whether used on Windows or Linux, this returns the correct full path to the assembly folder.

**Comment by RSuter** [comment]
v11.15.3
