### ISSUE TITLE
use of AcceptVerbsAttribute crashes json generation [aspnetcore] 

### ISSUE THREAD

**Issue by springy76** [RSuter/NSwag#1203]
I have a controller action attributed with `[HttpPost(""), AcceptVerbs("CustomVerb")]`. (Without the `AcceptVerbsAttribute` everything is fine.).

Instead of the swagger json I only get a text/plain result:

```
System.InvalidCastException: The object of type "WhereSelectArrayIterator`2[System.String,System.String]" cannot be converted to type "System.Collections.ICollection".
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GetSupportedHttpMethodsFromAttributes>d__24.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GetSupportedHttpMethods>d__23.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllerAsync>d__11.MoveNext()
--- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.<GenerateForControllersAsync>d__9.MoveNext()
--- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.AspNetCore.Middlewares.SwaggerMiddleware.<GenerateSwaggerAsync>d__8.MoveNext()
```

**Comment by springy76** [comment]
BTW: I can replace `[Route("test"), AcceptVerbs("PUT", "DELETE")]` with `[Route("test"), HttpPut, HttpDelete]` and I get what expected: 2 operations on the same route.
