### ISSUE TITLE
NSwagStudio v11.17.3.0 fails to start windows 10 version 1803 (OS Build 17134.1)

### ISSUE THREAD

**Issue by king4ever2u** [RSuter/NSwag#1313]
Fault bucket 1373729396796189076, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: NSwagStudio.exe
P2: 11.17.3.0
P3: 5ae327d2
P4: System.Xml
P5: 4.7.3056.0
P6: 5a8e5a09
P7: b85
P8: 27
P9: System.Xml.XmlException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCA3B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB17.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB28.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB26.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCB36.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_NSwagStudio.exe_764021a5f682c8a6c51b20ac68949a6590f818f9_06593e91_2b2ad344

Analysis symbol: 
Rechecking for solution: 0
Report Id: 24e3e694-9762-4c51-bf58-267e9faba308
Report Status: 268435456
Hashed bucket: ad9a9be4e2439967e310779ba98c6994
Cab Guid: 0

-----------------------------------------------------------------------------------------------------------

Faulting application name: NSwagStudio.exe, version: 11.17.3.0, time stamp: 0x5ae327d2
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1, time stamp: 0x701ca188
Exception code: 0xe0434352
Fault offset: 0x000000000003f218
Faulting process ID: 0x24c0
Faulting application start time: 0x01d3e51568d0314f
Faulting application path: C:\Program Files (x86)\Rico Suter\NSwagStudio\NSwagStudio.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 24e3e694-9762-4c51-bf58-267e9faba308
Faulting package full name: 
Faulting package-relative application ID: 

-----------------------------------------------------------------------------------------------

Application: NSwagStudio.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_Item()

Exception Info: System.InvalidOperationException
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.Xml.XmlReader, System.String, System.Xml.Serialization.XmlDeserializationEvents)
   at System.Xml.Serialization.XmlSerializer.Deserialize(System.IO.TextReader)
   at MyToolkit.Serialization.XmlSerialization.Deserialize[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Type[], Boolean)
   at MyToolkit.Serialization.XmlSerialization.DeserializeDictionary[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Type[], Boolean)
   at MyToolkit.Storage.ApplicationSettingsWpf.GetSetting[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Double, Boolean)
   at NSwagStudio.Views.MainWindow.LoadWindowState()
   at NSwagStudio.Views.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at NSwagStudio.App.Main()

-------------------------------------------------------------------------------------------------------

**Comment by RSuter** [comment]
Try to delete the NSwagStudio config before starting: 

C:\Users\MyUserName\AppData\Roaming\NSwagStudio

**Comment by darthmolen** [comment]
That fixed it but what and why?

**Comment by RSuter** [comment]
This is where NSwag stores the local config (using my http://mytoolkit.io library) i need to handle this error in this library: Create a new/delete existing file when reading fails...

**Comment by RSuter** [comment]
Probably it was corrupted or there was a breaking change (but i can't remember of any)...

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/MyToolkit/issues/98
