### ISSUE TITLE
NSwag.MSBuild stuck with "noBuild" false (11.17.21)

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1467]
No build progress when i use `aspNetCoreToSwagger` generator with `nobuild`: false.
nswag.json
```
        "aspNetCoreToSwagger": {
            "infoTitle": "WildApricot API Store specification",
            "project": "WildApricot.Api.Store.csproj",
            "noBuild": true,
             "verbose": false,
            "assemblyPaths": [],
            "referencePaths": [],
            "flattenInheritanceHierarchy": false,
            "generateKnownTypes": true,
            "defaultEnumHandling": "String",
            "defaultPropertyNameHandling": "CamelCase",
            "output": "swagger.json",
            "outputType": "Swagger2"
        }
```
.csproj:
```
  <Target Name="NSwag" AfterTargets="Build">
    <Exec Command="$(NSwagExe_Core21) run /variables:Configuration=$(Configuration)" />
  </Target>
```
output
```
  NSwag command line tool for .NET Core NetCore21, toolchain v11.17.21.0 (NJsonSchema v9.10.63.0 (Newtonsoft.Json v9.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\leef\.nuget\packages\nswag.msbuild\11.17.21\build\NetCore21

  Executing file 'nswag.json'...
  System.InvalidOperationException: Process dotnet timed out.
     at NSwag.Commands.SwaggerGeneration.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout)
     at NSwag.Commands.SwaggerGeneration.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, IConsoleHost console) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\ProjectMetadata.cs:line 141
     at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 65
     at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
     at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 36
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.Process(String[] args, Object input)
```

**Comment by RSuter** [comment]
The problem is that if noBuild = false, then you get into an endless recursion because you call nswag run in the csproj build and nswag run also rebuilds the project and so on...

**Comment by LeonidEfremov** [comment]
Totally agree. So, for `aspNetCoreToSwagger` i have always set `noBuild = true`... right?

**Comment by RSuter** [comment]
I think yes, but only if you run it in an after build target in csproj, if you run it standalone (i.e. only via nswag.exe or in NSwagStudio) then you probably need noBuild = false
