### ISSUE TITLE
Could not load file or assembly System.ServiceModel.Primitives

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1468]
When i have reference for nuget package `System.ServiceModel.Primitives` with version `4.5.2`, get exception

```
  Executing file 'nswag.json'...
  System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  File name: 'System.ServiceModel.Primitives, Version=4.5.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
  File name: 'System.ServiceModel.Primitives'
     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
     at System.Reflection.RuntimeAssembly.GetExportedTypes()
```
note, that `System.ServiceModel.Primitives` nuget bring assembly with version `4.6.26627.3`!
From other side i use version range >=4.5.2, and nswag can load higer version.

**Comment by RSuter** [comment]
Have you tried the tips from https://github.com/RSuter/NSwag/wiki/Assembly-loading ?

**Comment by LeonidEfremov** [comment]
Yes, all tips tried.

**Comment by prachh** [comment]
Any update on this question, I am facing the same issue.
