### ISSUE TITLE
System.IndexOutOfRangeException when generating an API client for Angular 6

### ISSUE THREAD

**Issue by gobbs** [RSuter/NSwag#1553]
When I am trying to generate an API client for Angular 6 I get the following error message: 

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
> 
> Runtime: NetCore21
>    at NSwag.Commands.NSwagDocumentBase.<>c.<ConvertVariables>b__42_2(String p) in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 286
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at NSwag.Commands.NSwagDocumentBase.ConvertVariables(String variables) in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 284
>    at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 183
> --- End of stack trace from previous location where exception was thrown ---
>    at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 69
>    at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 55
>    at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
>    at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
>    at NConsole.CommandLineProcessor.Process(String[] args, Object input)
>    at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

Any help would be much appreciated.

Here is my Swagger specification:

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "My API"
  },
  "paths": {
    "/api/ParaPhraser/parapagecontext": {
      "put": {
        "tags": [
          "ParaPhraser"
        ],
        "operationId": "ApiParaPhraserParapagecontextPut",
        "consumes": [
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "paraPC",
            "in": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ParaPageContext"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ParaPageContext"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ParaPageContext": {
      "type": "object",
      "properties": {
        "ParaContext": {
          "$ref": "#/definitions/ParaContext"
        },
        "BrowsingFromTo": {
          "$ref": "#/definitions/BrowsingFromTo"
        },
        "ParaMetersJSON": {
          "type": "string"
        }
      }
    },
    "ParaContext": {
      "type": "object",
      "properties": {
        "PWA": {
          "type": "string"
        },
        "ParaUrl": {
          "type": "string"
        },
        "ParaModelBase": {
          "type": "string"
        },
        "ParaAction": {
          "type": "string"
        },
        "POID": {
          "type": "string"
        },
        "ParaDateTime": {
          "type": "string"
        },
        "ParaGeo": {
          "type": "string"
        },
        "ParaUserType": {
          "type": "string"
        },
        "ORID": {
          "$ref": "#/definitions/ORID"
        },
        "OVersion": {
          "format": "int32",
          "type": "integer"
        },
        "OClassId": {
          "format": "int32",
          "type": "integer"
        },
        "OClassName": {
          "type": "string"
        }
      }
    },
    "BrowsingFromTo": {
      "type": "object",
      "properties": {
        "ParaUser": {
          "type": "string"
        },
        "ParaSession": {
          "type": "string"
        },
        "ParaGraph": {
          "type": "string"
        },
        "PageYOffset": {
          "format": "int32",
          "type": "integer"
        },
        "BrowserButton": {
          "type": "boolean"
        },
        "BrowsingDateTime": {
          "format": "date-time",
          "type": "string"
        },
        "ORID": {
          "$ref": "#/definitions/ORID"
        },
        "OVersion": {
          "format": "int32",
          "type": "integer"
        },
        "OClassId": {
          "format": "int32",
          "type": "integer"
        },
        "OClassName": {
          "type": "string"
        }
      }
    },
    "ORID": {
      "type": "object",
      "properties": {
        "ClusterId": {
          "format": "int32",
          "type": "integer"
        },
        "ClusterPosition": {
          "format": "int64",
          "type": "integer"
        },
        "RID": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by gobbs** [comment]
Hope this is what you are asking for:

```
{
  "runtime": "NetCore21",
  "defaultVariables": "https://localhost:44338/swagger/v1/swagger.json",
  "swaggerGenerator": {
    "fromSwagger": {
      "json": "{\r\n  \"swagger\": \"2.0\",\r\n  \"info\": {\r\n    \"version\": \"v1\",\r\n    \"title\": \"My API\"\r\n  },\r\n  \"paths\": {\r\n    \"/api/ParaPhraser/parapagecontext\": {\r\n      \"put\": {\r\n        \"tags\": [\r\n          \"ParaPhraser\"\r\n        ],\r\n        \"operationId\": \"ApiParaPhraserParapagecontextPut\",\r\n        \"consumes\": [\r\n          \"application/json-patch+json\",\r\n          \"application/json\",\r\n          \"text/json\",\r\n          \"application/*+json\"\r\n        ],\r\n        \"produces\": [\r\n          \"text/plain\",\r\n          \"application/json\",\r\n          \"text/json\"\r\n        ],\r\n        \"parameters\": [\r\n          {\r\n            \"name\": \"paraPC\",\r\n            \"in\": \"body\",\r\n            \"required\": false,\r\n            \"schema\": {\r\n              \"$ref\": \"#/definitions/ParaPageContext\"\r\n            }\r\n          }\r\n        ],\r\n        \"responses\": {\r\n          \"200\": {\r\n            \"description\": \"Success\",\r\n            \"schema\": {\r\n              \"$ref\": \"#/definitions/ParaPageContext\"\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"definitions\": {\r\n    \"ParaPageContext\": {\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"ParaContext\": {\r\n          \"$ref\": \"#/definitions/ParaContext\"\r\n        },\r\n        \"BrowsingFromTo\": {\r\n          \"$ref\": \"#/definitions/BrowsingFromTo\"\r\n        },\r\n        \"ParaMetersJSON\": {\r\n          \"type\": \"string\"\r\n        }\r\n      }\r\n    },\r\n    \"ParaContext\": {\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"PWA\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaUrl\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaModelBase\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaAction\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"POID\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaDateTime\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaGeo\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaUserType\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ORID\": {\r\n          \"$ref\": \"#/definitions/ORID\"\r\n        },\r\n        \"OVersion\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"OClassId\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"OClassName\": {\r\n          \"type\": \"string\"\r\n        }\r\n      }\r\n    },\r\n    \"BrowsingFromTo\": {\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"ParaUser\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaSession\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"ParaGraph\": {\r\n          \"type\": \"string\"\r\n        },\r\n        \"PageYOffset\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"BrowserButton\": {\r\n          \"type\": \"boolean\"\r\n        },\r\n        \"BrowsingDateTime\": {\r\n          \"format\": \"date-time\",\r\n          \"type\": \"string\"\r\n        },\r\n        \"ORID\": {\r\n          \"$ref\": \"#/definitions/ORID\"\r\n        },\r\n        \"OVersion\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"OClassId\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"OClassName\": {\r\n          \"type\": \"string\"\r\n        }\r\n      }\r\n    },\r\n    \"ORID\": {\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"ClusterId\": {\r\n          \"format\": \"int32\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"ClusterPosition\": {\r\n          \"format\": \"int64\",\r\n          \"type\": \"integer\"\r\n        },\r\n        \"RID\": {\r\n          \"type\": \"string\"\r\n        }\r\n      }\r\n    }\r\n  }\r\n}",
      "url": "https://localhost:44338/swagger/v1/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Service",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.7,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": true,
      "injectionTokenType": "InjectionToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "Date",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": false,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "paraplatform.api.ts"
    }
  }
}
```

**Comment by RSuter** [comment]
The defaultVariables must be the form "key1=value1,key2=value2", e.g. "Configuration=Debug"

    "defaultVariables": "https://localhost:44338/swagger/v1/swagger.json",
