### ISSUE TITLE
contains generic parameters error

### ISSUE THREAD

**Issue by dyesdyes** [RSuter/NSwag#1583]
Hello,

I get the following error:

> Executing file 'nswag.json'...
    System.ArgumentException: Type Api.Models.BaseApi.ApiResponse`1[TResult] contains generic parameters
    Parameter name: constructor
       at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Int32 index)
       at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Boolean allowByRef, Boolean allowPointer)
       at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
       at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.BuildMethodCall(MethodBase method, Type type, ParameterExpression targetParameterExpression, ParameterExpression argsParameterExpression)
       at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateParameterizedConstructor(MethodBase method)
       at Newtonsoft.Json.Serialization.JsonObjectContract.set_OverrideConstructor(ConstructorInfo value)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
       at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
       at NJsonSchema.Generation.DefaultReflectionService.GetDescription(Type type, IEnumerable`1 parentAttributes, JsonSchemaGeneratorSettings settings)
       at NSwag.SwaggerGeneration.WebApi.Processors.OperationParameterProcessor.ProcessAsync(OperationProcessorContext context) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\Processors\OperationParameterProcessor.cs:line 80
       at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.RunOperationProcessorsAsync(SwaggerDocument document, Type controllerType, MethodInfo methodInfo, SwaggerOperationDescription operationDescription, List`1 allOperations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 231
       at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.AddOperationDescriptionsToDocumentAsync(SwaggerDocument document, Type controllerType, List`1 operations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 201
       at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GenerateForControllerAsync(SwaggerDocument document, Type controllerType, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 189
       at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GenerateForControllersAsync(IEnumerable`1 controllerTypes) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 99
       at NSwag.Commands.SwaggerGeneration.WebApi.WebApiToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\WebApi\WebApiToSwaggerCommand.cs:line 77
       at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    --- End of stack trace from previous location where exception was thrown ---
       at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
       at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 49
       at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
       at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
       at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
       at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
       at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
       at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
       at NConsole.CommandLineProcessor.Process(String[] args, Object input)
       at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

Here is the ApiResponse class:

```
public class ApiResponse<T> : IApiResponse<T>, IApiResponse
    {
        private string _errorMessage;

        [JsonConstructor]
        public ApiResponse()
        {
        }

        public ApiResponse(T result)
        {
            Result = result;
        }

        public ApiResponse(params ApiError[] errors)
        {
            if (errors == null) return;
            foreach (var error in errors)
            {
                AddError(error);
            }
        }

        [JsonIgnore]
        public string ErrorMessage
        {
            get
            {
                if (_errorMessage == null && Errors != null)
                {
                    _errorMessage = string.Join(" ", Errors.Select(e => e.Description));
                }
                return _errorMessage;
            }
        }

        [JsonProperty(NullValueHandling = NullValueHandling.Include)]
        public IList<ApiError> Errors { get; set; } = new List<ApiError>();

        [JsonProperty(NullValueHandling = NullValueHandling.Include)]
        public T Result { get; set; }

        public void AddError(ApiError error)
        {
            Errors.Add(error);
        }
    }
```

So indeed, the constructor does have a generic parameter, I don't see why this is an issue.

**Comment by RSuter** [comment]
How is this class used in the controller?

**Comment by dyesdyes** [comment]
For the next people, I had some helper methods in the controller like: 

```
public ApiResult<TResult> Ok<TResult>(TResult result, int statusCode = StatusCodes.Status200OK)
        {
            return new ApiResult<TResult>(result, statusCode);
        }
```

Those need to be protected or private.
