### ISSUE TITLE
nswag.exe fails to run from unc path

### ISSUE THREAD

**Issue by usigrist** [RSuter/NSwag#1630]
If nswag.exe ist run from an UNC path the execution fails with an error message `
System.ArgumentException: URI formats are not supported.` 

Before the exception the console output shows the line `NSwag bin directory: file:\<sharename>\nswag\tools\win`. The UNC path is not formated correctly (only \\ instead of \\\\). 
I did look briefly into the code and saw that the Assembly.CodeBase property (along with some string replace) is used to print the `NSwag bin directory:` line. IMHO the Assembly.Location property would be a better choice. I did not check if the same code is used in other places which lead to the error.

**Comment by RSuter** [comment]
Can you post the full stack trace?

**Comment by usigrist** [comment]
```
\\<unc path>\Win\NSwag.exe webapi2swagger /assembly:xxx
NSwag command line tool for .NET 4.6.1+ WinX64, toolchain v11.18.7.0 (NJsonSchema v9.10.70.0 (Newtonsoft.Json v9.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: file:\<partial unc path>\NSwag\tools\Win
System.ArgumentException: URI formats are not supported.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.Reflection.RuntimeAssembly.VerifyCodeBase(String codebase)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at NSwag.AssemblyLoader.AppDomainIsolation`1..ctor(String assemblyDirectory, String assemblyConfiguration, IEnumerable`1 bindingRedirects, IEnumerable`1 preloadedAssemblies)
   at NSwag.Commands.IsolatedCommandBase`1.<RunIsolatedAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.<RunAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
```

**Comment by usigrist** [comment]
No the problem is that after \"file:\" the UNC path is not correct. It should be ``\\<share name>`` but it is ``\<share name>``. 
The output in the `NSwag bin directory` output (method `WriteBinDirectory` in [NSwagCommandProcessor.cs](https://github.com/RSuter/NSwag/blob/c2c3ad24fd1ef4e434a4a2fdc7c224c0c6f61771/src/NSwag.Commands/NSwagCommandProcessor.cs)) is correct, if the method `DynamicApis.PathGetDirectoryName` is called with `entryAssembly.Location` instead of `entryAssembly.CodeBase`. 
This method is not the problem since it is only used to write the path.
I assume the problem is that `DynamicApis.PathGetDirectoryName` (or some similar method) does not handle UNC path in an URI format correctly and that this leads to the error.

**Comment by RSuter** [comment]
So if i have `file:\abc\NSwag\tools\Win` i need to transform it to `\\<partial unc path>\NSwag\tools\Win`?

**Comment by usigrist** [comment]
`file:\abc\NSwag\tools\Win` is neither a correct URI nor a correct UNC path. 
Since `Assembly.CodeBase` is an URI the best way to transform it to a local path is `new Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath`. This works for local and for UNC path.
