### ISSUE TITLE
C# Client - NSwag.CodeGeneration.CSharp compatible with OpenAPI 3?

### ISSUE THREAD

**Issue by Ibro** [RSuter/NSwag#1684]
Is the C# client compatible with OpenAPI 3? I am trying to generate C# classes from JSON spec built on SwaggerHub.

I tried the NSWag GUI and `NSwag.CodeGeneration.CSharp` NuGet package, but it doesn't seem to work.

**Comment by RSuter** [comment]
Most of OpenAPI 3 features should be supported... 

> but it doesn't seem to work.

What's the error? what doesnt work?

**Comment by Ibro** [comment]
var json = await File.ReadAllTextAsync("openapi.json");
var document = await SwaggerDocument.FromJsonAsync(json, null, SchemaType.OpenApi3);

This fails.

Error:
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error setting value to 'DiscriminatorRaw' on 'NJsonSchema.JsonSchema4'. ---> Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'mapping.auto-accident'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at NJsonSchema.JsonSchema4.set_DiscriminatorRaw(Object value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
   at NSwag.SwaggerDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory)
   at OpenApi3CSharpClientGenerator.Program.Main(String[] args)
```

**Comment by RSuter** [comment]
There seems to be a problem with the discriminator in your spec... can you post the spec or the part which is failing ('mapping.auto-accident)?

**Comment by Ibro** [comment]
I can't share too much atm. I hope this is the relevant part:
```
"Incident" : {
  "discriminator" : {
    "propertyName" : "type",
    "mapping" : {
      "auto-accident" : "#/components/schemas/AutoIncidentAccident"
    }
  }
},
"AutoIncidentAccident" : {
  "allOf" : [ {
    "$ref" : "#/components/schemas/Incident"
  }, {
    "type" : "object",
    "properties" : {
      "prop1" : {
        "type" : "string",
        "enum" : [ "string1", "string2", "string3", "string4", "string5" ]
      },
      "prop2" : {
        "minimum" : 0,
        "type" : "integer",
        "format" : "int32"
      },
      "prop3" : {
        "type" : "boolean"
      }
    },
    "description" : "Description"
  } ]
},
```

**Comment by Ibro** [comment]
```{
    "Incident": {
        "required": [
            "subtype",
            "type"
        ],
        "type": "object",
        "properties": {
            "type": {
                "type": "string",
                "enum": [
                    "auto-accident",
                    "str2"
                ]
            },
            "date": {
                "type": "string",
                "format": "date"
            },
            "prop3": {
                "minimum": 0,
                "type": "integer",
                "description": "Description",
                "format": "int32"
            }
        },
        "discriminator": {
            "propertyName": "type",
            "mapping": {
                "auto-accident": "#/components/schemas/AutoIncidentAccident"
            }
        }
    },
    "AutoIncidentAccident": {
        "allOf": [
            {
                "$ref": "#/components/schemas/Incident"
            },
            {
                "type": "object",
                "properties": {
                    "prop1": {
                        "type": "string",
                        "enum": [
                            "string1",
                            "string2",
                            "string3",
                            "string4",
                            "string5"
                        ]
                    },
                    "prop2": {
                        "minimum": 0,
                        "type": "integer",
                        "format": "int32"
                    },
                    "prop3": {
                        "type": "boolean"
                    }
                },
                "description": "Description"
            }
        ]
    }
}```

Thanks for looking into this.

**Comment by RSuter** [comment]
use

```
 "discriminator": {
      "propertyName": "type",
      "mapping": {
        "auto-accident": 
          {
             "#/components/schemas/AutoIncidentAccident"
          } 
      }
    }

```

i.e. the value of auto-accident must be a JSON Schema with $ref (an object) and not a string

**Comment by Ibro** [comment]
```
  "auto-accident": 
            {
              "$ref": "#/components/schemas/AutoIncidentAccident"
            },
```

That worked. Thanks a lot!

**Comment by RSuter** [comment]
Oh yes, you are right... and again an inconsistency in the spec which will lead to ugly custom schema handling.

**Comment by InspiringCode** [comment]
Unfortunately I couldn't get a similar example get to work in the lastest version. I tried all the different ways to specifiy a mapping that were mentioned in this post. When I generate a TypeScript client, I get the exception:

> System.InvalidOperationException: Error while rendering Liquid template CSharp/Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The schema reference path '#/components/schemas/AutoIncidentAccident' has not been resolved.

>Runtime: NetCore21
   at NJsonSchema.JsonSchema.GetActualSchema(IList`1 checkedSchemas)
   at NJsonSchema.JsonSchema.get_ActualTypeSchema()
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel.<>c__DisplayClass0_0.<.ctor>b__0(KeyValuePair`2 m)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel..ctor(String typeName, JsonSchema schema, OpenApiDiscriminator discriminator, TypeResolverBase resolver)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.<get_DerivedClasses>b__13_0(KeyValuePair`2 p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   --- End of inner exception stack trace ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render() ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The schema reference path '#/components/schemas/AutoIncidentAccident' has not been resolved.
   at NJsonSchema.JsonSchema.GetActualSchema(IList`1 checkedSchemas)
   at NJsonSchema.JsonSchema.get_ActualTypeSchema()
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel.<>c__DisplayClass0_0.<.ctor>b__0(KeyValuePair`2 m)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel..ctor(String typeName, JsonSchema schema, OpenApiDiscriminator discriminator, TypeResolverBase resolver)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.<get_DerivedClasses>b__13_0(KeyValuePair`2 p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   --- End of inner exception stack trace ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateClass(JsonSchema schema, String typeName)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateTypes()
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in C:\projects\nswag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 75
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>b__83_0() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 242
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 228
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpClientCommand.cs:line 217
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56

**Comment by InspiringCode** [comment]
Here is a simple example JSON schema, which causes the exception. Just paste the JSON into NSwag Studio and click Generate Outputs.

`{
  "x-generator": "NSwag v13.0.4.0 (NJsonSchema v10.0.21.0 (Newtonsoft.Json v11.0.0.0))",
  "swagger": "2.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "host": "localhost:44377",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json-patch+json",
    "application/json",
    "text/json",
    "application/*+json"
  ],
  "produces": [
    "text/plain",
    "application/json",
    "text/json"
  ],
  "paths": {
    "/api/Command/{command}": {
      "get": {
        "tags": [
          "Command"
        ],
        "operationId": "Command_Post",
        "parameters": [
          {
            "name": "command",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Command"
            },
            "x-nullable": false
          },
          {
            "type": "string",
            "name": "command",
            "in": "path",
            "required": true,
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "x-nullable": false,
            "description": "",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Command": {
      "type": "object",
      "discriminator": {
      	"propertyName": "discriminator",
      	"mapping" : {
      	    "CreateCustomer": "CreateCustomer",
      	    "PrompoteCustomer": "PromoteCustomer"
      	}
      },
      "x-abstract": true,
      "required": [
        "discriminator"
      ],
      "properties": {
        "tenant": {
          "type": "string"
        },
        "discriminator": {
          "type": "string"
        }
      }
    },
    "CreateCustomer": {
      "allOf": [
        {
          "$ref": "#/definitions/Command"
        },
        {
          "type": "object",
          "required": [
            "dayOfBirth"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "dayOfBirth": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      ]
    },
    "PromoteCustomer": {
      "allOf": [
        {
          "$ref": "#/definitions/Command"
        },
        {
          "type": "object",
          "properties": {
            "reason": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}`
