### ISSUE TITLE
Updating Nest from 5.5 to 6.4 causes webapi2swagger to fail

### ISSUE THREAD

**Issue by Karzeus** [RSuter/NSwag#1691]
Hi.

Since I updated my Elasticsearch library for .NET Core (Nest), the webapi2swagger command fails and gives me the following exception:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Attribute' does not contain a definition for 'ConverterType'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at NJsonSchema.Generation.DefaultReflectionService.HasStringEnumConverter(IEnumerable`1 attributes)
   at NJsonSchema.Generation.DefaultReflectionService.IsStringEnum(Type type, IEnumerable`1 parentAttributes, JsonSchemaGeneratorSettings settings)
   at NJsonSchema.Generation.DefaultReflectionService.GetDescription(Type type, IEnumerable`1 parentAttributes, JsonSchemaGeneratorSettings settings)
   at NJsonSchema.Generation.JsonSchemaGenerator.<LoadPropertyOrFieldAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GeneratePropertiesAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateObjectAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.<GenerateObjectAsync>d__2.MoveNext() in C:\projects\nswag\src\NSwag.SwaggerGeneration\SwaggerJsonSchemaGenerator.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.<GenerateObjectAsync>d__2.MoveNext() in C:\projects\nswag\src\NSwag.SwaggerGeneration\SwaggerJsonSchemaGenerator.cs:line 49
```

I have rolledback to Nest 5.5.0 to make sure it is the cause of the problem, and it works perfectly.

I know that Nest 6.4 uses its own JsonSerializer, however I don't understand why this would affect NSwag.

My runtime is NetCore20 on Centos.

Could anyone help me with this issue?

Thanks,

Karzeus

**Comment by RSuter** [comment]
Can you provide simple sample app? It looks like there is a problem with one of the Nest DTOs which no have a different attribute implementation.

**Comment by RSuter** [comment]
And StringEnumConverter is not from Newtonsoft.Json but a Nest custom one?

**Comment by RSuter** [comment]
But it has the same effect?

**Comment by RSuter** [comment]
The commit avoids your exception but in your case it will detect your enum as int enum, because it seems that your JsonConverterAttribute does not have a ConverterType property and thus the StringEnumConverter cannot be checked...  Please review or provide more information of your scenario (e.g. exact JsonConverterAttribute/StringEnumConverter type/implementation)
