### ISSUE TITLE
msbuild - appsettings.json not found

### ISSUE THREAD

**Issue by lcssanches** [RSuter/NSwag#1834]
I am struggling for days to get this `msbuild` to work.

I don't know if I am doing something wrong, but I stucked at some errors.

```
 <Target Name="NSwag" AfterTargets="Build">
    <Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /assembly:$(TargetPath) /workingDirectory:$(TargetDir) /output:swagger.json" />
    <!--  <Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /project:CB.ERP.WebUI.csproj /output:swagger.json" /> -->
    <Exec Command="$(NSwagExe_Core21) swagger2tsclient /input:swagger.json /output:MyController.ts" />
  </Target>
```

Using /assembly I get this exception, failed to found appsettings.json.
```
6>------ Rebuild All started: Project: CB.ERP.WebUI, Configuration: Debug Any CPU ------
6>CB.ERP.WebUI -> E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.dll
6>CB.ERP.WebUI -> E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.Views.dll
6>NSwag command line tool for .NET Core NetCore21, toolchain v12.0.7.0 (NJsonSchema v9.13.4.0 (Newtonsoft.Json v11.0.0.0))
6>Visit http://NSwag.org for more information.
6>NSwag bin directory: C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21

6>System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21\appsettings.json'.

6>   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
6>   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
6>   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
6>   at CB.ERP.WebUI.Startup..ctor() in E:\Projetos\cb-erp\CB.ERP.WebUI\Startup.cs:line 37
6>--- End of stack trace from previous location where exception was thrown ---
6>   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
6>   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
6>   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
6>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
6>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
6>   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
6>   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
6>   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
6>   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
6>   at NSwag.Commands.SwaggerGeneration.SwaggerGeneratorCommandBase`1.CreateWebHostAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\SwaggerGeneratorCommandBase.cs:line 280
6>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 289
6>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 70
6>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
6>   at System.Threading.Tasks.Task`1.InnerInvoke()
6>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
6>--- End of stack trace from previous location where exception was thrown ---
6>   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
6>--- End of stack trace from previous location where exception was thrown ---
6>   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
6>   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
6>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 88
6>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
6>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
6>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
6>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
6>E:\Projetos\cb-erp\CB.ERP.WebUI\CB.ERP.WebUI.csproj(64,5): error MSB3073: The command "dotnet "C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\build\../tools/NetCore21/dotnet-nswag.dll" aspnetcore2swagger /assembly:E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.dll /output:swagger.json" exited with code -1.
6>Done building project "CB.ERP.WebUI.csproj" -- FAILED.
```

Using /project msbuild task hang forever, it "keep running" and even if I "Cancel the build" it doesn't cancel. To cancel I have to kill some "dotnet.exe" processes

```
6>------ Rebuild All started: Project: CB.ERP.WebUI, Configuration: Debug Any CPU ------
6>CB.ERP.WebUI -> E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.dll
6>CB.ERP.WebUI -> E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.Views.dll
6>NSwag command line tool for .NET Core NetCore21, toolchain v12.0.7.0 (NJsonSchema v9.13.4.0 (Newtonsoft.Json v11.0.0.0))
6>Visit http://NSwag.org for more information.
6>NSwag bin directory: C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21
6>Executing dotnet msbuild /nologo /verbosity:quiet /p:NSwagOutputMetadataFile=C:\Users\lcssa\AppData\Local\Temp\tmp4FFC.tmp /t:Build /t:__GetNSwagProjectMetadata CB.ERP.WebUI.csproj
6>System.InvalidOperationException: Process dotnet timed out.
6>   at NSwag.Commands.SwaggerGeneration.AspNetCore.Exe.RunAsync(String executable, IReadOnlyList`1 args, IConsoleHost console, Nullable`1 timeout)
6>   at NSwag.Commands.SwaggerGeneration.AspNetCore.ProjectMetadata.GetProjectMetadata(String file, String buildExtensionsDir, String framework, String configuration, String runtime, Boolean noBuild, IConsoleHost console) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\ProjectMetadata.cs:line 143
6>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 96
6>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
6>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
6>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
```

**Comment by RSuter** [comment]
I think working directory does not work because the path contains spaces, try /workingDirectory:”...”

When selecting project wth msbuild task you need to set noBuild to true to avoid endless rebuilds

**Comment by lcssanches** [comment]
Thank you @RSuter  for the fast reply.

There are no spaces in the path, but I tried anyway

```
<Exec Command='$(NSwagExe_Core21) aspnetcore2swagger /assembly:$(TargetPath) /output:swagger.json /workingDirectory:"$(TargetDir)"' />
```
Did not work. The wierd thing is that it left the quotation mark from the end.
```
1>System.IO.IOException: A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta : 'E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1"'
1>   at System.Environment.set_CurrentDirectoryCore(String value)
1>   at System.Environment.set_CurrentDirectory(String value)
1>   at System.IO.Directory.SetCurrentDirectory(String path)
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.ChangeWorkingDirectoryAndSetAspNetCoreEnvironment() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 228
1>   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 288
1>   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 70
1>   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
1>
```
------------
**With /noBuild:true it worked.**

```
<Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /project:CB.ERP.WebUI.csproj /noBuild:true /output:swagger.json" />
```
```
6>NSwag command line tool for .NET Core NetCore21, toolchain v12.0.7.0 (NJsonSchema v9.13.4.0 (Newtonsoft.Json v11.0.0.0))
6>Visit http://NSwag.org for more information.
6>NSwag bin directory: C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21
6>Executing dotnet msbuild /nologo /verbosity:quiet /p:NSwagOutputMetadataFile=C:\Users\lcssa\AppData\Local\Temp\tmpBABA.tmp /t:__GetNSwagProjectMetadata CB.ERP.WebUI.csproj
6>
6>
6>Done executing command. Exit Code: 0.
6>Done executing command
6>Output:
6>AssemblyName: CB.ERP.WebUI
6>OutputPath: bin\Debug\netcoreapp2.1\
6>PlatformTarget:
6>Platform: AnyCPU
6>ProjectDepsFilePath: E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.deps.json
6>ProjectDir: E:\Projetos\cb-erp\CB.ERP.WebUI\
6>ProjectRuntimeConfigFilePath: E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.runtimeconfig.json
6>TargetFileName: CB.ERP.WebUI.dll
6>TargetFrameworkIdentifier: .NETCoreApp
6>Executing dotnet exec --depsfile E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.deps.json --runtimeconfig E:\Projetos\cb-erp\CB.ERP.WebUI\bin\Debug\netcoreapp2.1\CB.ERP.WebUI.runtimeconfig.json C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21\NSwag.AspNetCore.Launcher.dll C:\Users\lcssa\AppData\Local\Temp\tmpBD99.tmp C:\Users\lcssa\AppData\Local\Temp\tmpBD9A.tmp CB.ERP.WebUI C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21\
6>Launcher directory: C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21
6>
6>
6>Done executing command. Exit Code: 0.
6>Output written to C:\Users\lcssa\AppData\Local\Temp\tmpBD9A.tmp.
6>Code has been successfully written to file.
6>
6>Duration: 00:00:04.4629046
6>NSwag command line tool for .NET Core NetCore21, toolchain v12.0.7.0 (NJsonSchema v9.13.4.0 (Newtonsoft.Json v11.0.0.0))
6>Visit http://NSwag.org for more information.
6>NSwag bin directory: C:\Users\lcssa\.nuget\packages\nswag.msbuild\12.0.7\tools\NetCore21
6>Code has been successfully written to file.
6>
6>Duration: 00:00:00.9269415
```

**Comment by lcssanches** [comment]
This was the final **working** msbuild, with more options.

```
  <Target Name="NSwag" AfterTargets="Build">
    <Exec Command="$(NSwagExe_Core21) aspnetcore2swagger /project:CB.ERP.WebUI.csproj /noBuild:true /output:swagger.json" />
    <Exec Command="$(NSwagExe_Core21) swagger2tsclient /input:swagger.json /output:ClientApp/src/app/cb-erp-api.ts /template:Angular /injectionTokenType:InjectionToken " />
  </Target>
```
