### ISSUE TITLE
nswag config overwritten by aspNetCoreToSwagger for project 

### ISSUE THREAD

**Issue by LeonidEfremov** [RSuter/NSwag#1886]
I use this config for C# client generation for Asp.NET Core Web API

```json
{
  "runtime": "default",
  "defaultVariables": "Configuration=Debug",
  "swaggerGenerator": {
    "AspNetCoreToSwagger": {
      "project": "../Server/Server.csproj",
      "configuration": "$(Configuration)",
      "noBuild": true,
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "namespace": "MyNamespace",
      "className": "MyClient",
      "clientBaseClass": "MyClientBase",
      "configurationClass": "MyConfiguration",
      "exposeBaseUrl": false,
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "generateDtoTypes": false,
      "generateSyncMethods": false,
      "generateBaseUrlProperty": true,
      "generateJsonMethods": false,
      "useBaseUrl": false,
      "injectHttpClient": true,
      "disposeHttpClient": false,
      "operationGenerationMode": "SingleClientFromOperationId",
      "additionalNamespaceUsages": [
        "System.Collections.Generic",
        "System.Net.Http"
      ],
      "httpClientType": "HttpClient",
      "arrayType": "IList",
      "arrayInstanceType": "List",
      "arrayBaseType": "List",
      "output": "Client.generated.cs"
    }
  }
}
```
after build this file replaced with full list properties for `aspNetCoreToSwagger` and `swaggerToCSharpClient` nodes.

Also, if i use multitargeting (2 client genarated), then i get exception

```
 System.IO.IOException: The process cannot access the file 'D:\Sources\MyProject\Client\nswag.json' bec
ause it is being used by another process.
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
     at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at NJsonSchema.Infrastructure.DynamicApis.FileWriteAllTextAsync(String filePath, String text)
     at NSwag.Commands.NSwagDocumentBase.<SaveAsync>b__37_0()
     at NSwag.Commands.NSwagDocumentBase.<>c__DisplayClass35_0`1.<<LoadAsync>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 205
  --- End of stack trace from previous location where exception was thrown ---
     at NSwag.Commands.NSwagDocument.LoadWithTransformationsAsync(String filePath, String variables) in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 69
     at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 55
     at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 36
     at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
     at NConsole.CommandLineProcessor.Process(String[] args, Object input)
     at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

**Comment by RSuter** [comment]
This is actually a feature, i.e. migrate the config file to the latest version :)

**Comment by LeonidEfremov** [comment]
Disagree, think it's wrong way to change foreign source code.

**Comment by LeonidEfremov** [comment]
Anyway, for multitargeting we get concurrent file access with IO exception.

**Comment by olstakh** [comment]
@RicoSuter what's the latest doc on migrating to the latest configuration version? We're getting the same issue with concurrent accesses

**Comment by RicoSuter** [comment]
Untouched. For me it would also be fine to remove this write entirely
