### ISSUE TITLE
Configuration=Release - Release folder is ignored

### ISSUE THREAD

**Issue by bleissem** [RSuter/NSwag#1985]
Hello, 
I try to run your sample
RSuter\NSwag\src\NSwag.Sample.NETCore22
and I got errors that I don't understand why they emerge.
What did I do:
- git clone https://github.com/RSuter/NSwag.git

- open up a console cmd and go to:
RSuter\NSwag\src\NSwag.Sample.NETCore22

- run 
dotnet build NSwag.Sample.NETCore22.csproj --configuration Release
As expected it uses the release folder under 
RSuter\NSwag\src\NSwag.SwaggerGeneration\bin\Release\netstandard2.0\
to generate dll's.

- run 
dotnet "C:\Users\user\.nuget\packages\nswag.msbuild\12.0.13\build\../tools/NetCore22/dotnet-nswag.dll" run .\nswag_project.nswag /runtime:NetCore22 /variables:Configuration=Release

I'm using the cached nswag.msbuild from nuget version 12.0.13 of nswag to run nswag to generate typescript code from the compiled assemblies in the bin/Release folder

By the way
dotnet --version
shows 2.2.104

I receive the following error:

System.InvalidOperationException: Project outputs could not be located in 'C:\Projects\github\RSuter\NSwag\src\NSwag.Sample.NETCore22\bin\Debug\netcoreapp2.2\'. Ensure that the project has been built.
   at NSwag.Commands.SwaggerGeneration.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs:line 173
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

Unfortunately it seems that the release folder is ignored since it has been configured as /variables:Configuration=Release
and nswag is looking inside the bin/debug folder and this folder is empty.

**Comment by RSuter** [comment]
The nswag config file is probably fixed to the debug output path

**Comment by RSuter** [comment]
The debug path is always used: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.Sample.NETCore22/nswag_assembly.nswag#L48

We'd need to change this to a variable placeholder and inject the variable in the `nswag run` cmd line call... (see wiki for sample)

**Comment by bleissem** [comment]
Hi @RSuter,
Ok, I see, thanks. 
I try to set a variable to the defaultVariables section and then assign it to the Configuration by using $(variable) syntax.

**Comment by stefanluchian** [comment]
I'm not sure I understand: Is there a way to take some other configuration than Debug?

**Comment by stefanluchian** [comment]
I figured it out myself.
One just needs to forward it through the file "nswag.json", like this:

![image](https://user-images.githubusercontent.com/58853386/110801104-2ba9c000-827d-11eb-9669-c055a43e90a8.png)

**Comment by Englund0110** [comment]
For future visitors, i will clarify what is needed.

In the nswag.json set this `"configuration": "$(Configuration)"`. 

And then in the .csproj set `$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)`

**Comment by KarlKl** [comment]
Ran into the exact same error a year later and wasted hours too.. Very frustrating.
I've followed the instructions in the wiki and there's no mention of it, just "Use a configuration file". Perhaps this can be added to the wiki? 🤔 That would be greatly appreciated. 🙂
