### ISSUE TITLE
Definition with allof and type:object with no properties causes Sequence contains no matching element error

### ISSUE THREAD

**Issue by RachelDavey4** [RSuter/NSwag#2028]
Hi,
I am trying to use NSwagStudio to generate C# from a swagger specification and am getting the following issue.

Definitions in the swagger which use inheritance through allof but do not add any additional properties to the object such as:
```Json
"definitions":    {
    "Dog": {
      "title": "Dog",
      "description": "",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object"
        }
      ]
    }
}
```
cause an error when trying to create DTO classes:
```
System.InvalidOperationException: Sequence contains no matching element

Runtime: Default
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.JsonSchema4.get_InheritedSchema()
   at NJsonSchema.JsonSchema4.<get_ActualProperties>b__44_0(JsonSchema4 s)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NJsonSchema.JsonSchema4.get_ActualProperties()
   at NJsonSchema.CodeGeneration.CSharp.Models.ClassTemplateModel..ctor(String typeName, CSharpGeneratorSettings settings, CSharpTypeResolver resolver, JsonSchema4 schema, Object rootObject)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateClass(JsonSchema4 schema, String typeName)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateTypes()
   at NSwag.CodeGeneration.CSharp.Models.CSharpFileTemplateModel.GenerateDtoTypes()
   at NSwag.CodeGeneration.CSharp.SwaggerToCSharpGeneratorBase.GenerateFile(String clientCode, IEnumerable`1 clientClasses, ClientGeneratorOutputType outputType)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<<RunAsync>b__86_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.NSwagDocument.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<ExecuteDocumentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.Document.ExecuteDocumentCommand.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
```

I have tried adding these types to the Excluded Type Names but am still get the same error.

Please can you let me know if there is a way of generating these classes.

Thanks,
Rachel

**Comment by RSuter** [comment]
Could not reproduce the problem, can you provide a complete spec?

**Comment by RachelDavey4** [comment]
I've mocked up a config file which causes this issue:

```
{
  "runtime": "Default",
  "defaultVariables": null,
  "swaggerGenerator": {
    "fromSwagger": {
      "json": "{\r\n  \"swagger\": \"2.0\",\r\n  \"info\": {\r\n    \"title\": \"TEST\",\r\n    \"description\": \"\",\r\n    \"version\": \"1.0\"\r\n  },\r\n  \"host\": \"test\",\r\n  \"basePath\": \"test/test\",\r\n  \"schemes\": [\r\n    \"https\"\r\n  ],\r\n  \"paths\": {\r\n    \"/TestPath\": {\r\n      \"get\": {\r\n        \"parameters\": [\r\n          {\r\n            \"in\": \"query\",\r\n            \"name\": \"MajorVersion\",\r\n            \"type\": \"number\",\r\n            \"description\": \"\",\r\n            \"required\": true,\r\n            \"default\": \"1\"\r\n          }\r\n        ],\r\n        \"produces\": [\r\n          \"application/json\"\r\n        ],\r\n        \"responses\": {\r\n          \"200\": {\r\n            \"description\": \"OK\",\r\n            \"schema\": {\r\n              \"items\": {\r\n                \"properties\": {\r\n                  \"ParameterizedEnquiryResponse\": {\r\n                    \"$ref\": \"#/definitions/ParameterizedEnquiryResponse\"\r\n                  }\r\n                }\r\n              },\r\n              \"type\": \"array\"\r\n            }\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"definitions\": {\r\n    \"RequestResultsType\": {\r\n      \"title\": \"RequestResultsType\",\r\n      \"description\": \"\",\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"Asset\": {\r\n          \"$ref\": \"#/definitions/AssetType\"\r\n        }\r\n      },\r\n      \"required\": [\r\n        \"Asset\"\r\n      ]\r\n    },\r\n    \"AssetType\": {\r\n      \"title\": \"AssetType\",\r\n      \"description\": \"\",\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"ParentData\": {\r\n          \"$ref\": \"#/definitions/ParentDataType\"\r\n        },\r\n        \"SupplementaryData\": {\r\n          \"$ref\": \"#/definitions/SupplementaryDataType\"\r\n        }\r\n      },\r\n      \"required\": [\r\n        \"AssetIdentification\"\r\n      ]\r\n    },\r\n    \"ParentDataType\": {\r\n      \"title\": \"ParentDataType\",\r\n      \"description\": \"\",\r\n      \"type\": \"object\"\r\n    },\r\n    \"SupplementaryDataType\": {\r\n      \"title\": \"SupplementaryDataType\",\r\n      \"description\": \"a\",\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"ChildDataType\": {\r\n          \"$ref\": \"#/definitions/ChildDataType\"\r\n        }\r\n      }\r\n    },\r\n    \"ChildDataType\": {\r\n      \"title\": \"ChildDataType\",\r\n      \"description\": \"\",\r\n      \"allOf\": [\r\n        {\r\n          \"$ref\": \"#/definitions/ParentDataType\"\r\n        },\r\n        {\r\n          \"type\": \"object\"\r\n        }\r\n      ]\r\n    },\r\n    \"ParameterizedEnquiryResponse\": {\r\n      \"title\": \"ParameterizedEnquiryResponse\",\r\n      \"description\": \"\",\r\n      \"type\": \"object\",\r\n      \"properties\": {\r\n        \"RequestResults\": {\r\n          \"$ref\": \"#/definitions/RequestResultsType\"\r\n        }\r\n      },\r\n      \"required\": [\r\n        \"RequestResults\"\r\n      ]\r\n    }\r\n  },\r\n  \"securityDefinitions\": {\r\n    \"basicAuth\": {\r\n      \"type\": \"basic\"\r\n    }\r\n  },\r\n  \"security\": [\r\n    {\r\n      \"basicAuth\": []\r\n    }\r\n  ]\r\n}",
      "url": "",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "clientBaseClass": "SwaggerRepository",
      "configurationClass": "TestOptions",
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "generateDtoTypes": true,
      "injectHttpClient": true,
      "disposeHttpClient": true,
      "protectedMethods": [],
      "generateExceptionClasses": true,
      "exceptionClass": "TestException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateBaseUrlProperty": false,
      "generateSyncMethods": false,
      "exposeJsonSerializerSettings": true,
      "clientClassAccessModifier": "internal",
      "typeAccessModifier": "public",
      "generateContractsOutput": false,
      "contractsNamespace": "",
      "contractsOutputFilePath": null,
      "parameterDateTimeFormat": "yyyy-MM-dd",
      "generateUpdateJsonSerializerSettingsMethod": true,
      "serializeTypeInformation": false,
      "queryNullValue": "",
      "className": "TestRepository",
      "operationGenerationMode": "MultipleClientsFromPathSegments",
      "additionalNamespaceUsages": [],
      "additionalContractNamespaceUsages": [],
      "generateOptionalParameters": true,
      "generateJsonMethods": true,
      "enforceFlagEnums": false,
      "parameterArrayType": "System.Collections.Generic.IEnumerable",
      "parameterDictionaryType": "System.Collections.Generic.IDictionary",
      "responseArrayType": "System.Collections.Generic.List",
      "responseDictionaryType": "System.Collections.Generic.IDictionary",
      "wrapResponses": true,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "{controller}Response",
      "namespace": "Test",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "jsonConverters": null,
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpannew",
      "arrayType": "System.Collections.Generic.List",
      "arrayInstanceType": "System.Collections.Generic.List",
      "dictionaryType": "System.Collections.Generic.IDictionary",
      "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "arrayBaseType": "System.Collections.Generic.List",
      "dictionaryBaseType": "System.Collections.Generic.Dictionary",
      "classStyle": "Record",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "jsonSerializerSettingsTransformationMethod": null,
      "inlineNamedDictionaries": false,
      "inlineNamedTuples": true,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": ""
    }
  }
}
```

**Comment by RSuter** [comment]
This is a really hard one as any schemas are usually not generated but just object/JObject... I've referenced a PR but it breaks a lot of other stuff.

**Comment by xaviergxf** [comment]
Hi @RicoSuter , i have the same problem do you know when this will be fixed?

Thanks

**Comment by RicoSuter** [comment]
Hard to fix without breaking changes and a edge case. So not on my prio list.
