### ISSUE TITLE
[MSBuild] PathTooLongException

### ISSUE THREAD

**Issue by pkupilas** [RSuter/NSwag#252]
I got an issue in msbuild. While NSwag searchs for assemblies the PathTooLongException appears. It's happening only in specific situation but still..

```
System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'myassembly' or one of its dependencies. The filename or extension is too long. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
5>     at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
5>     at System.IO.Path.GetDirectoryName(String path)
5>     at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
5>     at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
5>     at NSwag.CodeGeneration.SwaggerGenerators.AssemblyLoader.<>c__DisplayClass0_0.<RegisterReferencePaths>b__1(Object sender, ResolveEventArgs args)
5>     at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
5>     --- End of inner exception stack trace ---
```

I googled it and found this [post](http://stackoverflow.com/questions/530109/how-to-avoid-system-io-pathtoolongexception).
Is it possible to consider external libs like Delimon.Win32.I​O to avoid this problem?

**Comment by rsuter** [comment]
Maybe .NET 4.6.2 solves this problem: http://stackoverflow.com/a/38889598/876814

**Comment by pkupilas** [comment]
Well after changes in .net framework versions:

**4.6.2 NSwag && NSwagStudio** - DirectoryNotFoundException
```
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'MyAssembly, Version=0.0.1.0, Culture=neutral, PublicKeyToken=485d6168b1ae96cc' or one of its dependencies. The system cannot find the path specified. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\gitrepo\mfxi\External Tools\swagger-merger\node_modules\swagger-merge\node_modules\swagger2-utils\node_modules\z-schema\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules'.
5>     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
5>     at System.IO.FileSystemEnumerableIterator`1.CommonInit()
5>     at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
5>     at NSwag.CodeGeneration.SwaggerGenerators.AssemblyLoader.<>c__DisplayClass0_0.<RegisterReferencePaths>b__1(Object sender, ResolveEventArgs args) in C:\Users\piotrku\Documents\tmp\Nswagv5\NSwag-master\src\NSwag.AssemblyLoader\SwaggerGenerators\AssemblyLoader.cs:line 35
5>     at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
5>     --- End of inner exception stack trace ---
```




**4.6 NSwag && NSwagStudio** - PathTooLongException
```
System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'MyAssembly, Version=0.0.1.0, Culture=neutral, PublicKeyToken=485d6168b1ae96cc' or one of its dependencies. The filename or extension is too long. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
5>     at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
5>     at System.IO.Path.InternalGetDirectoryName(String path)
5>     at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
5>     at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
5>     at NSwag.CodeGeneration.SwaggerGenerators.AssemblyLoader.<>c__DisplayClass0_0.<RegisterReferencePaths>b__1(Object sender, ResolveEventArgs args) in C:\Users\piotrku\Documents\tmp\Nswagv5\NSwag-master\src\NSwag.AssemblyLoader\SwaggerGenerators\AssemblyLoader.cs:line 35
5>     at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
5>     --- End of inner exception stack trace ---
```

Are you sure MSBuild and VS are supported with this _MAX_PATH_ change?
According to your [source](https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/#bcl) (comments).
> Petr Vones
After many years the legacy MAX_PATH limitation is gone. Thanks ! Will also MSBuild and Visual Studio take advantage of it ?

> JeremyKuhne
Not yet. Getting the blocks removed from .NET is the first step to making MAX_PATH a thing of the past. 

> Immo Landwerth [MSFT]
We haven’t yet updated the VM to support loading DLLs on long paths. So take this feature in .NET Framework 4.6.2 as a large step in the right direction, but don’t expect that Long Path issues are completely gone yet.

**Comment by rsuter** [comment]
Are you using the recently released .net v4.6.2?

**Comment by pkupilas** [comment]
It's working now with v5 due to changes in #242.

**Comment by rsuter** [comment]
Really? Why did this solve this issue here? The paths are still too long, or not?

**Comment by pkupilas** [comment]
After changes in #242 I don't use `@referencepaths` so NSwag doesn't need to look through whole solution because paths to dlls are already known (NSwag doesn't get into this unfortunate folder).

**Comment by rsuter** [comment]
I think this is just "luck", the problem itself is not solved... But i dont know how easy it is to fix...

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.

**Comment by RSuter** [comment]
Closing as not seen for a long time...
