### ISSUE TITLE
NSwagStudio v11.5.0 fails to start

### ISSUE THREAD

**Issue by akamyshanov** [RSuter/NSwag#908]
The latest version installed via `.msi` for some reason fails to start. All I can say is that the previous version worked well. Seems that some dependency is either missing on my machine or a DLL was not copied to the installer.

Console app seems to start fine.

Error events:

```
Log Name:      Application
Source:        .NET Runtime
Date:          29/08/2017 19:41:35
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Windows-Dev
Description:
Application: NSwagStudio.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException

Exception Info: System.IO.FileLoadException
   at NSwagStudio.App.InitializeTelemetry()
   at NSwagStudio.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-08-29T16:41:35.190386400Z" />
    <EventRecordID>7960</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Windows-Dev</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: NSwagStudio.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException

Exception Info: System.IO.FileLoadException
   at NSwagStudio.App.InitializeTelemetry()
   at NSwagStudio.App.Main()

</Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Application Error
Date:          29/08/2017 19:41:35
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Windows-Dev
Description:
Faulting application name: NSwagStudio.exe, version: 11.5.0.0, time stamp: 0x59a58f91
Faulting module name: KERNELBASE.dll, version: 10.0.15063.502, time stamp: 0x005405b5
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process id: 0xe34
Faulting application start time: 0x01d320e5ad4fd61a
Faulting application path: C:\Program Files (x86)\Rico Suter\NSwagStudio\NSwagStudio.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 579e32cc-645f-42dd-9e30-129feb023fe1
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-08-29T16:41:35.237144500Z" />
    <EventRecordID>7961</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Windows-Dev</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NSwagStudio.exe</Data>
    <Data>11.5.0.0</Data>
    <Data>59a58f91</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.15063.502</Data>
    <Data>005405b5</Data>
    <Data>e0434352</Data>
    <Data>0000000000069e08</Data>
    <Data>e34</Data>
    <Data>01d320e5ad4fd61a</Data>
    <Data>C:\Program Files (x86)\Rico Suter\NSwagStudio\NSwagStudio.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>579e32cc-645f-42dd-9e30-129feb023fe1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by RSuter** [comment]
Oh this is bad. Will fix this in the next hours...

**Comment by RSuter** [comment]
The CI build is broken, try this for now:

[NSwagStudio.zip](https://github.com/RSuter/NSwag/files/1261410/NSwagStudio.zip)

**Comment by akamyshanov** [comment]
v11.5.1 works fine, thank you for the prompt response.

**Comment by RSuter** [comment]
v11.5.1 works for me too. 
Sorry for any inconveniences.
